version: '3.8'

services:
  recommendation-system-book-frontend:
    build:
      context: .  # Assurez-vous que le Dockerfile et le code sont dans le même répertoire
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
